version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: focos-ia-chat-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - focos-ia-network

  redis:
    image: redis:7-alpine
    container_name: focos-ia-chat-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - focos-ia-network

volumes:
  postgres_data:
  redis_data:

networks:
  focos-ia-network:
    driver: bridge