export { api } from './api'
export * as authService from './auth/auth.service'
export * as uploadService from './upload/upload.service'
export { socketService } from './websocket/socket.service'
export { applicationService } from './application/application.service'
export * as contactService from './contact/contact.service'
export * as tagService from './tag/tag.service'
export * as userService from './user/user.service'
export * as roleService from './role/role.service'
export * as whatsappService from './whatsapp/whatsapp.service'

export * from '../types'